apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n5network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ovs",
    "bridge": "n5",
    "ipam": {
      "type": "host-local",
      "subnet": "10.10.5.0/24",
      "rangeStart": "10.10.5.100",
      "rangeEnd": "10.10.5.200"
    }
  }'
