apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-server
spec:
  replicas: 12  # We'll create 12 video servers (6 data + 6 parity as per paper)
  selector:
    matchLabels:
      app: video-server
  template:
    metadata:
      labels:
        app: video-server
    spec:
      containers:
      - name: video-server
        image: tomcat:9.0-alpine
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: video-server
spec:
  clusterIP: None  # Headless service for individual pod access
  selector:
    app: video-server
  ports:
  - port: 8080
    targetPort: 8080
