apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: video-server-upf1-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ovs",
    "bridge": "n3",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.10.3.101/24"
        }
      ]
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: video-server-upf2-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ovs",
    "bridge": "n3",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.10.3.102/24"
        }
      ]
    }
  }'
