apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-upf5
  labels:
    app: open5gs
    nf: upf
    name: upf5
spec:
  selector:
    matchLabels:
      app: open5gs
      nf: upf
      name: upf5
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs
        nf: upf
        name: upf5
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.5/24" ] },
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.5/24" ] }
          ]'
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: cn201

      initContainers:
      - name: wait-smf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: smf1-nsmf:80
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the SMF; sleep 2; done;"]
      containers:
      - name: upf
        image: ghcr.io/niloysh/open5gs:v2.6.4-aio
        imagePullPolicy: Always
        command: [ "/open5gs/config/wrapper.sh" ]
        volumeMounts:
        - mountPath: /open5gs/config/
          name: upf-volume
        ports:
        - containerPort: 8805
          name: n4
          protocol: UDP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes:
      - name: upf-volume
        configMap:
          name: upf5-configmap
          items:
          - key: upfcfg.yaml
            path: upfcfg.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0777
