apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  clusterIP: None
  selector:
    app: tomcat
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: video-client-svc
spec:
  type: NodePort
  selector:
    app: video-client
  ports:
    - port: 80
      targetPort: 80

